import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../globals.css";
import { NextFont } from "next/dist/compiled/@next/font";
import { FC, PropsWithChildren } from "react";

import { Header } from "@/shared/ui/header";
import StoreProvider from "@/app/providers/store/StoreProvider";
import { NotificationAlert } from "@/shared/ui/notificationAlert";
import { WebSocketProvider } from "@/app/providers/websockets";

const inter: NextFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Market",
  description: "Generated by create next app",
  icons: "/logo.png",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <StoreProvider>
      <WebSocketProvider>
        <html lang="ru">
          <body className={inter.className}>
            <Header>{children}</Header>
            <NotificationAlert></NotificationAlert>
          </body>
        </html>
      </WebSocketProvider>
    </StoreProvider>
  );
};

export default RootLayout;
